"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.group import Group
globals()['Group'] = Group
from openapi_client.model.list_groups200_response import ListGroups200Response


class TestListGroups200Response(unittest.TestCase):
    """ListGroups200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListGroups200Response(self):
        """Test ListGroups200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListGroups200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
