"""
    Johns API

    Demo API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.groups_api import GroupsApi  # noqa: E501


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_create(self):
        """Test case for groups_create

        """
        pass

    def test_groups_destroy(self):
        """Test case for groups_destroy

        """
        pass

    def test_groups_list(self):
        """Test case for groups_list

        """
        pass

    def test_groups_partial_update(self):
        """Test case for groups_partial_update

        """
        pass

    def test_groups_retrieve(self):
        """Test case for groups_retrieve

        """
        pass

    def test_groups_update(self):
        """Test case for groups_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
