"""
    Johns API

    Demo API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.patched_user_request import PatchedUserRequest


class TestPatchedUserRequest(unittest.TestCase):
    """PatchedUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedUserRequest(self):
        """Test PatchedUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
