"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user import User
globals()['User'] = User
from openapi_client.model.list_users200_response import ListUsers200Response


class TestListUsers200Response(unittest.TestCase):
    """ListUsers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListUsers200Response(self):
        """Test ListUsers200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListUsers200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
