"""
    Johns API

    Demo API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.group import Group
globals()['Group'] = Group
from openapi_client.model.paginated_group_list import PaginatedGroupList


class TestPaginatedGroupList(unittest.TestCase):
    """PaginatedGroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedGroupList(self):
        """Test PaginatedGroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedGroupList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
