"""
    Johns API

    Demo API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.group_request import GroupRequest


class TestGroupRequest(unittest.TestCase):
    """GroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupRequest(self):
        """Test GroupRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
